def stampa_menu():
    print('\nMenu:')
    print('| Opzione | Descrizione                          |')
    print('|---------|--------------------------------------|')
    print('| 1       | Visualizza la classifica aggiornata  |')
    print('| 2       | Imposta una sfida                    |')
    print('| 3       | Esito sfide                          |')
    print('| 4       | Segnala Giocatore infortunato        |')
    print('| 5       | Segnala Giocatore Idoneo             |')
    print('| 6       | Cancella giocatore                   |')
    print('| 7       | Aggiungi Giocatore                   |')
    print('| 8       | Visualizza sfide in corso            |')
    print('| 9       | Visualizza stato giocatori           |')
    print('| 10      | Exit programma                       |')